<?php
/**
 * GENERATED by tools/build_wordpress.py. Do not edit.
 *
 * slug => [ body class, data-nav key ]
 *
 * The body class drives the design: `t-home` and `t-shop` change the page
 * shell's background and the header's colour logic, so a page with the wrong
 * one renders in the wrong palette. The nav key highlights the current menu
 * item, and is handed to the front end as window.AP_NAV.
 */
defined( 'ABSPATH' ) || exit;

function ap_page_map() : array {
	return [
		'about' => [ 't-inner t-about', 'about' ],
		'acrylic-pool-panels' => [ 't-inner t-legacy -overlay page page--pool-panels', 'services' ],
		'acrylic-sign-fabrication' => [ 't-inner t-legacy -overlay page', 'services' ],
		'aquarium-relocations' => [ 't-inner t-legacy -overlay page', 'services' ],
		'contact' => [ 't-inner t-contact', '' ],
		'custom-builds-installations' => [ 't-inner t-legacy -overlay page page--custom-builds', 'services' ],
		'emergency-services' => [ 't-inner t-legacy -overlay page page--emergency', 'services' ],
		'gallery' => [ 't-inner t-gallery', 'gallery' ],
		'glass-tanks' => [ 't-inner t-shop', 'glass-tanks' ],
		'front' => [ 't-home', 'home' ],
		'live-corals' => [ 't-inner t-legacy -overlay page page--live-corals', 'services' ],
		'maintenance' => [ 't-inner t-legacy -overlay page page--maintenance', 'services' ],
		'pond-design-construction' => [ 't-inner t-legacy -overlay page page--pond', 'services' ],
		'privacy-policy' => [ 't-inner t-legacy -overlay page page--privacy-policy', '' ],
		'process' => [ 't-inner t-process', 'process' ],
		'quote' => [ 't-inner t-quote', '' ],
		'reef-insert-restoration' => [ 't-inner t-legacy -overlay page page--reef-insert', 'services' ],
		'refund-policy' => [ 't-inner t-legacy -overlay page page--refund-policy', '' ],
		'scratch-removal' => [ 't-inner t-legacy -overlay page page--scratch-removal', 'services' ],
		'services' => [ 't-inner t-services', 'services' ],
		'sharks' => [ 't-inner t-legacy -overlay page page--sharks', 'services' ],
		'stingrays-eels' => [ 't-inner t-legacy -overlay page page--stingrays-eels', 'services' ],
		'tropical-fish' => [ 't-inner t-legacy -overlay page page--tropical-fish', 'services' ],
		'videos' => [ 't-inner t-videos', 'videos' ],
		'warranty' => [ 't-inner t-legacy -overlay page page--warranty', '' ],
	];
}

/** Every product page carries the same shell classes. */
function ap_product_body_class() : string {
	return 't-inner t-shop t-product';
}
