<?php
/**
 * GENERATED by tools/build_wordpress.py from the pages' meta blocks.
 * Do not edit.
 *
 * The preload hint for each page's largest image. In the static build these
 * sit in <head>; WordPress owns <head>, so they are re-emitted here or they
 * are simply lost, and the hero image on 14 pages loses its head start.
 *
 * Priority 2 on wp_head: after the nav key at 1, and before WordPress prints
 * the enqueued stylesheet at 8 — a preload that arrives after the stylesheet
 * it was meant to race has done nothing.
 */
defined( 'ABSPATH' ) || exit;

function ap_preloads() : array {
	return [
		'acrylic-pool-panels' => '<link rel="preload" as="image" href="/wp-content/uploads/project-25-960.webp" type="image/webp" fetchpriority="high">',
		'acrylic-sign-fabrication' => '<link rel="preload" as="image" href="/wp-content/uploads/project-35-756.webp" type="image/webp" fetchpriority="high">',
		'aquarium-relocations' => '<link rel="preload" as="image" href="/wp-content/uploads/project-30-540.webp" type="image/webp" fetchpriority="high">',
		'custom-builds-installations' => '<link rel="preload" as="image" href="/wp-content/uploads/reef-tank-white-stand-1600.webp" type="image/webp" fetchpriority="high">',
		'emergency-services' => '<link rel="preload" as="image" href="/wp-content/uploads/project-18-540.webp" type="image/webp" fetchpriority="high">',
		'front' => '<link rel="preload" as="image" href="/wp-content/uploads/hero-poster-desktop-1280.webp" type="image/webp" media="(min-width: 641px)" fetchpriority="high">',
		'live-corals' => '<link rel="preload" as="image" href="/wp-content/uploads/coral-closeup-header-1280.webp" type="image/webp" fetchpriority="high">',
		'maintenance' => '<link rel="preload" as="image" href="/wp-content/uploads/kitchen-aquarium-lifestyle-1239.webp" type="image/webp" fetchpriority="high">',
		'pond-design-construction' => '<link rel="preload" as="image" href="/wp-content/uploads/koi-pond-lilies-1600.webp" type="image/webp" fetchpriority="high">',
		'reef-insert-restoration' => '<link rel="preload" as="image" href="/wp-content/uploads/coral-closeup-header-1920.webp" type="image/webp" fetchpriority="high">',
		'scratch-removal' => '<link rel="preload" as="image" href="/wp-content/uploads/scratch-removal-header-1280.webp" type="image/webp" media="(min-width: 641px)" fetchpriority="high"><link rel="preload" as="image" href="/wp-content/uploads/scratch-removal-header-768.webp" type="image/webp" media="(max-width: 640px)" fetchpriority="high">',
		'sharks' => '<link rel="preload" as="image" href="/wp-content/uploads/underwater-godrays-bg-1920.webp" type="image/webp" fetchpriority="high">',
		'stingrays-eels' => '<link rel="preload" as="image" href="/wp-content/uploads/underwater-godrays-bg-1920.webp" type="image/webp" fetchpriority="high">',
		'tropical-fish' => '<link rel="preload" as="image" href="/wp-content/uploads/coral-closeup-header-1280.webp" type="image/webp" fetchpriority="high">',
	];
}

add_action( 'wp_head', function () {
	$all = ap_preloads();
	$key = null;

	if ( is_front_page() ) {
		$key = 'front';
	} else {
		$obj = get_queried_object();
		if ( $obj instanceof WP_Post && isset( $all[ $obj->post_name ] ) ) {
			$key = $obj->post_name;
		}
	}

	if ( null === $key ) {
		return;
	}

	// Already-escaped markup generated from our own source, not user input.
	echo $all[ $key ] . "\n";
}, 2 );
