#!/usr/bin/env python3
"""Assemble the static HTML pages from src/.

Why a build step for a "static site": the header, footer, floating contact
panel and <head> boilerplate are identical on every page. Hand-copying them
into two dozen files guarantees drift — one nav change becomes 26 edits and
the 27th gets forgotten. Here the chrome lives once in src/partials/ and
each page contributes only its own composition, which stays hand-authored
and deliberately different per page.

The OUTPUT is plain static HTML with no runtime dependency. Nothing about
the deployed site requires Python.

    python tools/build_pages.py            # build every page
    python tools/build_pages.py --check    # fail if output is stale

IMPORTANT: generated pages are overwritten. Edit src/pages/*.html, never
the built file in the project root.
"""
import io
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "src")
PAGES = os.path.join(SRC, "pages")
PARTIALS = os.path.join(SRC, "partials")
SCHEMA = os.path.join(SRC, "schema")

SITE_URL = "https://acrylicpros.com/"

GENERATED_NOTE = (
    "<!-- Generated by tools/build_pages.py from src/pages/%s.\n"
    "     Edit that file, not this one. -->\n"
)

DEFAULTS = {
    "OG_TYPE": "website",
    "TOP_CLASS": "",
    "BODY_CLASS": "page",
    "OG_IMAGE": "assets/images/hero/hero-poster-desktop.jpg",
    "OG_IMAGE_ALT": "A reef aquarium built by Acrylic Pros.",
    "PRELOAD": "",
}

META_RE = re.compile(r"^\s*<!--meta\s*(.*?)-->", re.S)

# {{> name}} pulls in src/partials/name.html. Used for machine-generated
# blocks such as the gallery grid and the product catalogue, so those stay
# regenerable without hand-editing a page.
INCLUDE_RE = re.compile(r"\{\{>\s*([a-z0-9\-_]+)\s*\}\}")


def expand_includes(text, depth=0):
    if depth > 5:
        sys.exit("include nesting too deep — check for a cycle in src/partials/")

    def swap(match):
        name = match.group(1)
        path = os.path.join(PARTIALS, name + ".html")
        if not os.path.isfile(path):
            sys.exit("include not found: src/partials/%s.html" % name)
        return expand_includes(read(path), depth + 1)

    return INCLUDE_RE.sub(swap, text)


def read(path):
    with io.open(path, encoding="utf-8") as f:
        return f.read()


def parse_page(path):
    """Split a source page into its meta block and its body markup."""
    raw = read(path)
    m = META_RE.match(raw)
    if not m:
        sys.exit("%s: missing a leading <!--meta ... --> block" % os.path.basename(path))
    meta = dict(DEFAULTS)
    for line in m.group(1).splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if ":" not in line:
            sys.exit("%s: cannot parse meta line %r" % (os.path.basename(path), line))
        key, value = line.split(":", 1)
        meta[key.strip().upper()] = value.strip()
    return meta, raw[m.end():].lstrip("\n")


def build():
    check_only = "--check" in sys.argv

    def partial(name):
        path = os.path.join(PARTIALS, name + ".html")
        if not os.path.isfile(path):
            sys.exit("partial not found: src/partials/%s.html" % name)
        return read(path)

    sources = sorted(n for n in os.listdir(PAGES) if n.endswith(".body.html"))
    if not sources:
        sys.exit("No page sources found in src/pages/")

    stale = []
    written = 0

    for name in sources:
        slug = name[: -len(".body.html")]
        src_path = os.path.join(PAGES, name)
        meta, body = parse_page(src_path)
        body = expand_includes(body)

        meta.setdefault("CANONICAL", "" if slug == "index" else slug + ".html")
        if slug == "index":
            meta["CANONICAL"] = ""
        meta.setdefault("OG_TITLE", meta.get("TITLE", ""))
        meta.setdefault("OG_DESCRIPTION", meta.get("DESCRIPTION", ""))
        if "OG_TITLE" not in meta or not meta["OG_TITLE"]:
            meta["OG_TITLE"] = meta["TITLE"]
        if "OG_DESCRIPTION" not in meta or not meta["OG_DESCRIPTION"]:
            meta["OG_DESCRIPTION"] = meta["DESCRIPTION"]
        meta["SITE_URL"] = SITE_URL

        for required in ("TITLE", "DESCRIPTION"):
            if not meta.get(required):
                sys.exit("%s: meta %s is required" % (name, required.lower()))

        # A page may swap in its own chrome (the homepage does):
        #   head: home-head / header: home-header / footer: home-footer
        head = partial(meta.get("HEAD", "head"))
        header = partial(meta.get("HEADER", "header"))
        footer_tpl = partial(meta.get("FOOTER", "footer"))
        for key, value in meta.items():
            token = "{{%s}}" % key
            head = head.replace(token, value)
            header = header.replace(token, value)
        # Any token the page did not supply collapses to empty.
        head = re.sub(r"\{\{[A-Z_]+\}\}", "", head)
        header = re.sub(r"\{\{[A-Z_]+\}\}", "", header)

        # Structured data, if the page ships any.
        schema_block = ""
        schema_name = meta.get("SCHEMA")
        if schema_name:
            schema_path = os.path.join(SCHEMA, schema_name + ".json")
            if not os.path.isfile(schema_path):
                sys.exit("%s: schema file not found: %s" % (name, schema_path))
            schema_block = (
                '\n<script type="application/ld+json">\n'
                + read(schema_path).strip()
                + "\n</script>\n"
            )

        # The main landmark wrapper is part of the default chrome only; a page
        # with its own header partial opens and closes <main> itself.
        main_open, main_close = ('<main id="main">', "</main>") if "HEADER" not in meta else ("", "")
        out = (
            head
            + "\n"
            + header
            + main_open
            + body
            + main_close
            + footer_tpl
            + schema_block
            + "\n</body>\n</html>\n"
        )
        out = GENERATED_NOTE % name + out

        dest = os.path.join(ROOT, slug + ".html")
        existing = read(dest) if os.path.isfile(dest) else None
        if existing != out:
            stale.append(slug + ".html")
            if not check_only:
                with io.open(dest, "w", encoding="utf-8") as f:
                    f.write(out)
                written += 1

    if check_only:
        if stale:
            print("STALE (rebuild needed): " + ", ".join(stale))
            return 1
        print("All %d page(s) up to date." % len(sources))
        return 0

    print("Built %d page(s); %d changed." % (len(sources), written))
    for slug in stale:
        print("  wrote " + slug)
    return 0


if __name__ == "__main__":
    sys.exit(build())
