#!/usr/bin/env python3
"""Build the homepage Instagram feed from data/instagram.json.

    python tools/build_instagram.py            # write src/partials/instagram-feed.html
    python tools/build_instagram.py --refresh  # first re-download every post cover

A static site cannot call the Instagram API without a token, so the feed is a
snapshot: each tile is the post's cover image and links to the real post.
To show newer posts, put their links at the top of data/instagram.json
(with a short caption), run with --refresh, then run build_images.py,
this script again and build_pages.py. --refresh needs Playwright + Chrome.
"""
import html
import io
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, "data", "instagram.json")
MANIFEST = os.path.join(ROOT, "assets", "image-manifest.json")
OUT = os.path.join(ROOT, "src", "partials", "instagram-feed.html")


def refresh(posts):
    from playwright.sync_api import sync_playwright
    with sync_playwright() as p:
        browser = p.chromium.launch(channel="chrome")
        ctx = browser.new_context(viewport={"width": 540, "height": 900})
        page = ctx.new_page()
        for i, post in enumerate(posts):
            code = re.search(r"/(?:reel|p)/([^/]+)/", post["link"]).group(1)
            post["image"] = "assets/images/instagram/post-%02d.jpg" % (i + 1)
            page.goto("https://www.instagram.com/p/%s/embed/" % code, wait_until="load", timeout=40000)
            page.wait_for_timeout(2500)
            src = page.evaluate("""() => { const i = [...document.images]
                .filter(x => x.naturalWidth >= 300)
                .sort((a, b) => b.naturalWidth - a.naturalWidth)[0]; return i ? i.currentSrc : null; }""")
            if not src:
                print("  !! no image for %s" % post["link"])
                continue
            body = ctx.request.get(src).body()
            io.open(os.path.join(ROOT, post["image"]), "wb").write(body)
            print("  saved %s (%d KB)" % (post["image"], len(body) // 1024))
        browser.close()
    io.open(DATA, "w", encoding="utf-8").write(json.dumps(posts, ensure_ascii=False, indent=1) + "\n")


def main():
    posts = json.load(io.open(DATA, encoding="utf-8"))
    if "--refresh" in sys.argv:
        refresh(posts)
    manifest = json.load(io.open(MANIFEST, encoding="utf-8"))
    tiles = []
    for post in posts:
        entry = manifest.get(post["image"][len("assets/"):])
        if not entry:
            print("  !! %s missing from the manifest (run build_images.py)" % post["image"])
            continue
        srcset = ", ".join("%s %dw" % (d["path"], d["w"]) for d in entry["webp"])
        cap = html.escape(post["caption"])
        tiles.append(
            '<li class="m-igTile"><a href="%s" target="_blank" rel="noopener">'
            '<picture><source type="image/webp" srcset="%s" sizes="(min-width: 1025px) 15vw, 45vw">'
            '<img src="%s" alt="%s" width="%d" height="%d" loading="lazy" decoding="async"></picture>'
            '<span class="m-igTile__play" aria-hidden="true"><svg class="a-svg"><use href="#i-play"/></svg></span>'
            '<span class="m-igTile__caption">%s</span>'
            '<span class="sr-only"> (Instagram, opens in a new tab)</span></a></li>'
            % (html.escape(post["link"]), srcset, post["image"], cap, entry["w"], entry["h"], cap))
    io.open(OUT, "w", encoding="utf-8").write(
        "<!-- Generated by tools/build_instagram.py from data/instagram.json -->\n" + "\n".join(tiles) + "\n")
    print("Wrote %d Instagram tiles to src/partials/instagram-feed.html" % len(tiles))


if __name__ == "__main__":
    main()
