#!/usr/bin/env python3
"""Download Plus Jakarta Sans woff2 for self-hosting.

Google serves woff2 only to browsers that advertise support, so we send a
modern Chrome UA, parse the returned @font-face blocks, and save each file.
Emits assets/fonts/fonts.css with rewritten local src paths.
"""
import os
import re
import urllib.request

ROOT = r"C:\Users\varun\OneDrive\Desktop\s20\digital-heroes\acrylicpros"
FONT_DIR = os.path.join(ROOT, "assets", "fonts")
UA = {"User-Agent": ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                     "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")}

FAMILIES = [
    ("plus-jakarta-sans",
     "https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:ital,wght@0,500;0,600;0,700;0,800;1,500&display=swap"),
]

os.makedirs(FONT_DIR, exist_ok=True)
out_css = []
saved = 0

for slug, url in FAMILIES:
    with urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=60) as r:
        css = r.read().decode("utf-8")

    # Only keep latin + latin-ext subsets; drop cyrillic/greek/vietnamese to save weight.
    blocks = re.split(r"(?=/\*\s*[a-z-]+\s*\*/)", css)
    for block in blocks:
        subset = re.search(r"/\*\s*([a-z-]+)\s*\*/", block)
        if not subset or subset.group(1) not in ("latin", "latin-ext"):
            continue
        src = re.search(r"url\((https://[^)]+\.woff2)\)", block)
        if not src:
            continue
        weight = re.search(r"font-weight:\s*([^;]+);", block)
        style = re.search(r"font-style:\s*([^;]+);", block)
        w = (weight.group(1).strip() if weight else "400").replace(" ", "-")
        s = style.group(1).strip() if style else "normal"
        name = "%s-%s-%s-%s.woff2" % (slug, subset.group(1), w, s)
        dest = os.path.join(FONT_DIR, name)
        if not (os.path.exists(dest) and os.path.getsize(dest) > 0):
            with urllib.request.urlopen(urllib.request.Request(src.group(1), headers=UA), timeout=60) as fr:
                data = fr.read()
            with open(dest, "wb") as f:
                f.write(data)
            saved += 1
        out_css.append(block.replace(src.group(1), "./" + name).strip())

header = ("/* Self-hosted webfonts. Generated by tools/fetch_fonts.py.\n"
          "   Plus Jakarta Sans is SIL Open Font License 1.1.\n"
          "   Latin and Latin-Extended subsets only. */\n\n")
with open(os.path.join(FONT_DIR, "fonts.css"), "w", encoding="utf-8") as f:
    f.write(header + "\n\n".join(out_css) + "\n")

print("saved %d woff2 files to assets/fonts/" % saved)
print("total files:", len([n for n in os.listdir(FONT_DIR) if n.endswith(".woff2")]))
